# MH 4/15/13 - state DB config info 
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
adapter: postgresql
encoding: unicode
database: my_app_production
pool: 5
username: my_app
password:


cucumber:
  <<: *test